library(terra)
library(ncdf4)
library(dplyr)
library(tidyr)
library(readxl)
library(tidyterra)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(RColorBrewer)
library(patchwork)
library(lubridate)
library(tidyverse)
library(metR)
library(akima)
library(ggquiver)
library(viridis)
library(ggh4x)
library(grid)


sea_ice <- read.csv("C:/Users/USER/Downloads/df_sea_ice.csv")
